services:
  nginx:
    image: nginx:alpine
    container_name: pbra_nginx
    environment:
      - TZ=Asia/Singapore
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/PBRA:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - php
      - db
    restart: always

  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pbra_php
    volumes:
      - ../docker/PBRA:/var/www/html
    env_file:
      - ../docker/PBRA/.env
    environment:
      - TZ=Asia/Singapore
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    container_name: pbra_db
    restart: always
    env_file:
      - ../docker/PBRA/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Singapore
    ports:
      - "3306:3306"
    volumes:
      - pbradatabases:/var/lib/mysql
      - ../docker/PBRA/pbradatabases.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pbra_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - TZ=Asia/Singapore
    depends_on:
      - db

  certbot:
    image: certbot/certbot
    container_name: pbra_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
   # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --post-hook \"nginx -s reload\"; sleep 12h & wait $!; done;'"

volumes:
  pbradatabases:
