services:
  nginx:
    image: nginx:alpine
    container_name: pbra_nginx
    environment:
      - TZ=Asia/Singapore
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pbra_php
    volumes:
      - ../:/var/www/html
    env_file:
      - .env
    environment:
      - TZ=Asia/Singapore
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    container_name: pbra_db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Singapore
    ports:
      - "3306:3306"
    volumes:
      - pbradatabases:/var/lib/mysql
      - ../pbradatabases.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pbra_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - TZ=Asia/Singapore
    depends_on:
      - db

volumes:
  pbradatabases: